<?php

namespace AppBundle\Repository;

/**
 * address_interventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class address_interventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function addressesNotExist($name){
        $response = true;
        $results = $this->createQueryBuilder('a')
            ->where('a.name = :nameAdr')
            ->setParameter('nameAdr' , $name)
            ->getQuery()
            ->getResult()
        ;
        if (!empty($results)){
            $response = false;
        }

        return $response;
    }
}
