<?php

namespace AppBundle\Repository;

/**
 * address_interventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class address_interventionRepository extends \Doctrine\ORM\EntityRepository
{
}
