<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function categoryNotExist($name)
    {
        $response = true;
        $results = $this->createQueryBuilder('category')
            ->where('category.name = :vname')
            ->setParameter('vname', $name)
            ->getQuery()
            ->getResult();
        if (!empty($results)) {
            $response = false;
        }

        return $response;
    }

    public function nextPositionAvailable()
    {
        $result = $this->createQueryBuilder('category')
            ->select('category, MAX(category.position) as last_position')
            ->getQuery()
            ->getResult();
        // cas ou il n'existe aucune categorie
        if ($result == null || empty($result)) $result = 0;
        //on incremente de 1 pour avoir la position suivante
        return $result + 1;
    }

    public function findAllOrderByPosition(){
        $results = $this->createQueryBuilder('category')
            ->orderBy('category.position')
            ->getQuery()
            ->getResult()
        ;

        return $results;
    }


}
