<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Annee;
use AppBundle\Entity\Mois;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function referenceNotExist($ref){
        $response = true;
        $results = $this->createQueryBuilder('command')
            ->andwhere('command.ref = :ref')
            ->setParameter('ref' , $ref)
            ->getQuery()
            ->getResult()
        ;
        if (!empty($results)){
            $response = false;
        }

        return $response;
    }

    public function billReferenceNotExist($ref){
        $response = true;
        $results = $this->createQueryBuilder('command')
            ->andwhere('command.billRef = :ref')
            ->setParameter('ref' , $ref)
            ->getQuery()
            ->getResult()
        ;
        if (!empty($results)){
            $response = false;
        }

        return $response;
    }

    public function findOneOrderByPositionMagic($id)
    {
        $results = $this->createQueryBuilder('command')
            ->addSelect('cmdservice')
            ->addSelect('service')
            ->addSelect('category')
            ->join('command.commandsServices', 'cmdservice')
            ->join('cmdservice.service', 'service')
            ->join('service.category', 'category')
            ->andWhere('command.id = :id')
            ->setParameter('id' , $id)
            ->orderBy('category.position')
            ->getQuery()
            ->getResult();

        return $results;
    }

    public function findFactureAcquitedByYear(Annee $annee){
        $results = $this->createQueryBuilder('command')

            ->andWhere('command.dateBillAcquited IS NOT NULL')
            ->andWhere('YEAR(command.dateBill) = :annee')
            ->setParameter('annee' , $annee->getCode())
            ->getQuery()
            ->getResult();

        return $results;
    }

    public function findFactureAcquitedByYearAndMonth(Annee $annee,Mois $mois){
        $results = $this->createQueryBuilder('command')

            ->andWhere('command.dateBillAcquited IS NOT NULL')
            ->andWhere('YEAR(command.dateBill) = :annee')
            ->setParameter('annee' , $annee->getCode())
            ->andWhere('MONTH(command.dateBill) = :mois')
            ->setParameter('mois' , $mois->getCode())
            ->getQuery()
            ->getResult();

        return $results;
    }

    public function findDevisByYearAndMonth(int $annee,int $mois){
        $results = $this->createQueryBuilder('command')

            ->andWhere('command.dateBill IS NULL')
            ->andWhere('YEAR(command.dateCreate) = :annee')
            ->setParameter('annee' , $annee)
            ->andWhere('MONTH(command.dateCreate) = :mois')
            ->setParameter('mois' , $mois)
            ->orderBy('command.dateCreate')
            ->getQuery()
            ->getResult();

        return $results;
    }

    public function findFacturesByYearAndMonth(int $annee,int $mois){
        $results = $this->createQueryBuilder('command')

            ->andWhere('command.dateBill IS NOT NULL')
            ->andWhere('YEAR(command.dateBill) = :annee')
            ->setParameter('annee' , $annee)
            ->andWhere('MONTH(command.dateBill) = :mois')
            ->setParameter('mois' , $mois)
            ->orderBy('command.dateBill')
            ->getQuery()
            ->getResult();

        return $results;
    }

}
