<?php

namespace AppBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function referenceNotExist($ref){
        $response = true;
        $results = $this->createQueryBuilder('command')
            ->andwhere('command.ref = :ref')
            ->setParameter('ref' , $ref)
            ->getQuery()
            ->getResult()
        ;
        if (!empty($results)){
            $response = false;
        }

        return $response;
    }

}
