<?php

namespace AppBundle\Repository;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function referenceNotExist($ref){
        $response = true;
        $results = $this->createQueryBuilder('command')
            ->andwhere('command.ref = :ref')
            ->setParameter('ref' , $ref)
            ->getQuery()
            ->getResult()
        ;
        if (!empty($results)){
            $response = false;
        }

        return $response;
    }

    public function billReferenceNotExist($ref){
        $response = true;
        $results = $this->createQueryBuilder('command')
            ->andwhere('command.billRef = :ref')
            ->setParameter('ref' , $ref)
            ->getQuery()
            ->getResult()
        ;
        if (!empty($results)){
            $response = false;
        }

        return $response;
    }

    public function findOneOrderByPositionMagic($id)
    {
        $results = $this->createQueryBuilder('command')
            ->addSelect('cmdservice')
            ->addSelect('service')
            ->addSelect('category')
            ->join('command.commandsServices', 'cmdservice')
            ->join('cmdservice.service', 'service')
            ->join('service.category', 'category')
            ->andWhere('command.id = :id')
            ->setParameter('id' , $id)
            ->orderBy('category.position')
            ->getQuery()
            ->getResult();

        return $results;
    }

}
