<?php

namespace AppBundle\Repository;

/**
 * CommandsServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandsServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
