<?php

namespace AppBundle\Repository;

/**
 * PaymentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function paymentTypeNotExist($name)
    {
        $response = true;
        $results = $this->createQueryBuilder('PaymentType')
            ->where('PaymentType.name = :vname')
            ->setParameter('vname', $name)
            ->getQuery()
            ->getResult();
        if (!empty($results)) {
            $response = false;
        }

        return $response;
    }

}
