<?php

namespace AppBundle\Repository;

/**
 * ResultatMensuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatMensuelRepository extends \Doctrine\ORM\EntityRepository
{
}
