<?php

namespace AppBundle\Repository;

/**
 * ResultatAnnuelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatAnnuelRepository extends \Doctrine\ORM\EntityRepository
{
}
