<?php

namespace AppBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function serviceNotExist($name){
        $response = true;
        $results = $this->createQueryBuilder('service')
            ->where('service.name = :vname')
            ->setParameter('vname' , $name)
            ->getQuery()
            ->getResult()
        ;
        if (!empty($results)){
            $response = false;
        }

        return $response;
    }

}
