<?php

namespace AppBundle\Repository;

/**
 * TaxRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxRateRepository extends \Doctrine\ORM\EntityRepository
{
    public function tvaNotExist($value)
    {
        $response = true;
        $results = $this->createQueryBuilder('tva')
            ->where('tva.value = :vname')
            ->setParameter('vname', $value)
            ->getQuery()
            ->getResult();
        if (!empty($results)) {
            $response = false;
        }

        return $response;
    }

}
