<?php

namespace AppBundle\Repository;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends \Doctrine\ORM\EntityRepository
{
    public function vehiculeNotExist($registration){
        $response = true;
        $results = $this->createQueryBuilder('vehicule')
            ->where('vehicule.registration = :regis')
            ->setParameter('regis' , $registration)
            ->getQuery()
            ->getResult()
        ;
        if (!empty($results)){
            $response = false;
        }

        return $response;
    }
}
